//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public System.DateTime SigningDate { get; set; }
        public int Amount { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ObjectId { get; set; }
    
        public virtual Object Object { get; set; }
        public virtual User User { get; set; }
    }
}
