//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.Booking = new HashSet<Booking>();
            this.Contract = new HashSet<Contract>();
            this.ObjectPhoto = new HashSet<ObjectPhoto>();
        }
    
        public int Id { get; set; }
        public int RoomCount { get; set; }
        public int Area { get; set; }
        public string Address { get; set; }
        public int StatusId { get; set; }
        public int TypeOfSubjectId { get; set; }
        public int TypeOfDealId { get; set; }
        public int Price { get; set; }
        public int OwnerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeOfDeal TypeOfDeal { get; set; }
        public virtual TypeOfSubject TypeOfSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectPhoto> ObjectPhoto { get; set; }
    }
}
