//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectPhoto
    {
        public int Id { get; set; }
        public int ObjectId { get; set; }
        public string PhotoUrl { get; set; }
    
        public virtual Object Object { get; set; }
    }
}
